title: I am Zihan (Michelle) Fan, a student at Entertainment Technology Center, Carnegie Mellon University.
logo: /assets/img/IMG_5652.JPG
description: Design-oriented HCI researcher | Prospective PhD applicant
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
