title: I am Zihan (Michelle) Fan, a student at Entertainment Technology Center, Carnegie Mellon University.
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
